# Generated by Django 5.0.1 on 2024-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_amount_productamount_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='cook_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
